development:
  adapter : postgresql
  database: configparser_development
  encoding: unicode
  password: postgres
  pool    : 5
  username: postgres
# host    : 192.168.1.70
production:
  adapter : postgresql
  database: configparser_production
  encoding: unicode
  password: postgres
  pool    : 5
  username: postgres
test:
  adapter:  postgresql
  database: configparser_test
  encoding: unicode
  password: postgres
  pool    : 5
  username: postgres
  host    : 192.168.1.70